# Generated by Django 4.2.1 on 2023-07-12 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(blank=True, default='', max_length=20)),
                ('position_size', models.FloatField()),
                ('quantity_usdt', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('type_of_pos', models.CharField(blank=True, max_length=5)),
                ('leverage', models.IntegerField()),
                ('open_price', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_versiob', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(blank=True, default='', max_length=20)),
                ('position_size', models.FloatField()),
                ('quantity_usdt', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('type_of_pos', models.CharField(blank=True, max_length=5)),
                ('leverage', models.IntegerField()),
                ('price', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ClosingLimitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('position_size', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('type_of_order', models.CharField(blank=True, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='exchange.position')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
