# Generated by Django 4.2.1 on 2023-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_order_type_of_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
