# Generated by Django 4.2.1 on 2023-07-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_historypnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypnl',
            name='roe',
            field=models.FloatField(null=True),
        ),
    ]
