# Generated by Django 4.2.1 on 2023-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_order_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='open_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
