# Generated by Django 4.2.1 on 2023-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_order_type_of_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position_size',
            field=models.FloatField(default=0.11),
            preserve_default=False,
        ),
    ]
