# Generated by Django 4.2.1 on 2023-06-30 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0007_limitorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Position',
        ),
    ]
