# Generated by Django 4.2.1 on 2023-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_limitorder_type_of_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='quantity_usdt',
            field=models.FloatField(),
        ),
    ]
